//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRPORT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANE
    {
        public int ID { get; set; }
        public string PLACE { get; set; }
        public int SPEED { get; set; }
        public int IDTYPE { get; set; }
    
        public virtual TYPE TYPE { get; set; }
    }
}
