//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRPORT.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETS
    {
        public int ID { get; set; }
        public int SELLTICKETS { get; set; }
        public int IDPATH { get; set; }
    
        public virtual PATH PATH { get; set; }
    }
}
